version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: todo-mongodb
    ports:
     - "27017:27017"
    networks:
     - todo-network

  backend:
     image: todo-backend
     container_name: todo-backend
     ports:
      - "5000:5000"
     depends_on:
      -  mongodb
     networks:
      - todo-network

  frontend:
    image: todo-frontend
    container_name: todo-frontend
    ports :
      - "9092:80"
    depends_on:
      - backend
    networks:
      - "todo-network"


networks:
  todo-network:
    driver: bridge
